-- ==========================================
-- 유럽 중고거래 통합 데이터베이스 스키마
-- ==========================================

-- 1. Profiles Table (사용자 프로필)
create table if not exists public.profiles (
  id uuid references auth.users on delete cascade primary key,
  username text unique,
  full_name text,
  avatar_url text,
  website text,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on public.profiles for select
  using (true);

create policy "Users can insert their own profile."
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Users can update own profile."
  on public.profiles for update
  using (auth.uid() = id);

-- 2. Posts Table (중고거래, 알바, 과외, 모임 등 통합 게시글)
create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade,
  title text not null,
  description text,
  price text,
  location text,
  country_code text not null,
  category text, -- 'used', 'job', 'tutoring', 'meetup'
  image_urls text[] default '{}'::text[],
  views integer default 0,
  likes integer default 0,
  trade_time text,
  latitude double precision,
  longitude double precision,
  metadata jsonb default '{}'::jsonb,
  education text, -- 과외 카테고리용
  subject text,   -- 과외 카테고리용
  time_ago text,  -- legacy (필요시 프론트엔드 계산 권장)
  color text,     -- legacy (UI용 색상)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.posts enable row level security;

create policy "Public posts are viewable by everyone."
  on public.posts for select
  using (true);

create policy "Authenticated users can insert their own posts."
  on public.posts for insert
  with check (auth.authenticated() and auth.uid() = user_id);

create policy "Users can update their own posts."
  on public.posts for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete their own posts."
  on public.posts for delete
  using (auth.uid() = user_id);

create index if not exists posts_user_id_idx on public.posts(user_id);
create index if not exists posts_category_idx on public.posts(category);
create index if not exists posts_country_code_idx on public.posts(country_code);

-- 3. Conversations Table (채팅방)
create table if not exists public.conversations (
  id uuid default gen_random_uuid() primary key,
  participant1_id uuid references public.profiles(id) on delete cascade not null,
  participant2_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete set null,
  last_message text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  constraint participants_distinct check (participant1_id != participant2_id)
);

alter table public.conversations enable row level security;

create policy "Users can view their own conversations"
  on public.conversations for select
  using (auth.uid() = participant1_id or auth.uid() = participant2_id);

create policy "Users can create conversations"
  on public.conversations for insert
  with check (auth.uid() = participant1_id or auth.uid() = participant2_id);

create policy "Users can update their own conversations"
  on public.conversations for update
  using (auth.uid() = participant1_id or auth.uid() = participant2_id);

-- 4. Messages Table (채팅 메시지)
create table if not exists public.messages (
  id uuid default gen_random_uuid() primary key,
  conversation_id uuid references public.conversations(id) on delete cascade not null,
  sender_id uuid references public.profiles(id) on delete cascade not null,
  content text not null,
  is_read boolean default false,
  image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.messages enable row level security;

create policy "Users can view messages in their conversations"
  on public.messages for select
  using (
    exists (
      select 1 from public.conversations
      where id = messages.conversation_id
      and (participant1_id = auth.uid() or participant2_id = auth.uid())
    )
  );

create policy "Users can send messages"
  on public.messages for insert
  with check (
    auth.uid() = sender_id and
    exists (
      select 1 from public.conversations
      where id = messages.conversation_id
      and (participant1_id = auth.uid() or participant2_id = auth.uid())
    )
  );

-- 5. Popular Snapshots (인기 항목 스냅샷 - 일일 집계용)
create table if not exists public.popular_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  country_code text default 'ALL'::text,
  top_items jsonb not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- ==========================================
-- Functions & Triggers
-- ==========================================

-- 프로필 자동 생성 함수
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (
    new.id, 
    new.raw_user_meta_data->>'nickname', 
    new.raw_user_meta_data->>'full_name', 
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (id) do update set
    username = excluded.username,
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url;
  return new;
end;
$$ language plpgsql security definer;

-- Auth 회원가입 트리거
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 조회수 원자적 증가 함수
create or replace function public.increment_views(post_id bigint)
returns void as $$
begin
  update public.posts
  set views = views + 1
  where id = post_id;
end;
$$ language plpgsql security definer;

-- 채팅방 중복 생성 방지 및 조회 함수
create or replace function public.get_or_create_conversation(p1_id uuid, p2_id uuid, target_post_id bigint default null)
returns uuid as $$
declare
  conv_id uuid;
begin
  -- 기존 채팅방 확인 (참가자 순서와 관계없이)
  select id into conv_id
  from public.conversations
  where 
    (participant1_id = p1_id and participant2_id = p2_id)
    or 
    (participant1_id = p2_id and participant2_id = p1_id);

  if conv_id is null then
    insert into public.conversations (participant1_id, participant2_id, post_id)
    values (p1_id, p2_id, target_post_id)
    returning id into conv_id;
  end if;

  return conv_id;
end;
$$ language plpgsql security definer;
