-- 1. Posts Table (기존에 없다면 생성, 있다면 views 필드 추가)
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    price TEXT, -- 유로/파운드 등 단위 포함 문자로 저장하거나, 별도 currency 컬럼 사용 가능
    location TEXT,
    time_ago TEXT, -- '1분 전' 등 (실제로는 created_at을 사용해야 함)
    color TEXT, -- 썸네일 배경색 (임시)
    country_code TEXT NOT NULL, -- 'FR', 'DE', 'GB' ...
    views INTEGER DEFAULT 0,
    likes INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Popular Snapshots Table (일자별 TOP 10 저장)
CREATE TABLE IF NOT EXISTS public.popular_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_date DATE NOT NULL UNIQUE, -- '2024-02-07' (하루에 하나만 존재)
    country_code TEXT DEFAULT 'ALL', -- 국가별 스냅샷이 필요하다면 사용 (현재는 전체/국가별 로직에 따라 다름. 일단 'ALL'로 통합 저장하거나 JSON 구조로 해결)
    -- 여기서는 전체 TOP 10만 저장한다고 가정하거나, JSON 내부에 국가별 정보를 포함할 수 있습니다.
    -- 요구사항: "전체는 전체 top10이여야 하고 나라를 선택하면 특정 나라의 top10이 되어야해"
    -- 따라서 스냅샷은 '국가별'로 각각 생성되거나, 하나의 큰 JSON에 다 들어있어야 합니다.
    -- 효율성을 위해: snapshot_date + country_code를 복합 키로 사용하는 것이 좋습니다.
    
    top_items JSONB NOT NULL, -- TOP 10 아이템 리스트 (JSON 배열)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 복합 유니크 키 설정 (날짜 + 국가코드)
ALTER TABLE public.popular_snapshots 
ADD CONSTRAINT unique_date_country UNIQUE (snapshot_date, country_code);

-- 3. Function to aggregate TOP 10 (30분마다 호출될 함수)
CREATE OR REPLACE FUNCTION generate_daily_top10(target_date DATE)
RETURNS VOID AS $$
DECLARE
    countries TEXT[] := ARRAY['ALL', 'FR', 'DE', 'GB', 'NL', 'IT', 'AT', 'HU', 'CZ']; -- 지원 국가 목록
    c_code TEXT;
    top_list JSONB;
BEGIN
    -- 1. 전체(ALL) TOP 10 집계
    SELECT jsonb_agg(t) INTO top_list
    FROM (
        SELECT id, title, price, location, time_ago as time, color, country_code as country, views, likes
        FROM public.posts
        WHERE created_at >= target_date::timestamp
          AND created_at < (target_date + 1)::timestamp
        ORDER BY views DESC
        LIMIT 10
    ) t;

    -- 데이터가 없으면 빈 배열 저장 방지 또는 빈 배열 저장 (선택 사항)
    IF top_list IS NULL THEN top_list := '[]'::jsonb; END IF;

    -- Upsert (있으면 업데이트, 없으면 삽입)
    INSERT INTO public.popular_snapshots (snapshot_date, country_code, top_items, updated_at)
    VALUES (target_date, 'ALL', top_list, now())
    ON CONFLICT (snapshot_date, country_code)
    DO UPDATE SET top_items = EXCLUDED.top_items, updated_at = now();

    -- 2. 국가별 TOP 10 집계 Loop
    FOREACH c_code IN ARRAY countries
    LOOP
        IF c_code != 'ALL' THEN
            SELECT jsonb_agg(t) INTO top_list
            FROM (
                SELECT id, title, price, location, time_ago as time, color, country_code as country, views, likes
                FROM public.posts
                WHERE country_code = c_code
                  AND created_at >= target_date::timestamp
                  AND created_at < (target_date + 1)::timestamp
                ORDER BY views DESC
                LIMIT 10
            ) t;

            IF top_list IS NULL THEN top_list := '[]'::jsonb; END IF;

            INSERT INTO public.popular_snapshots (snapshot_date, country_code, top_items, updated_at)
            VALUES (target_date, c_code, top_list, now())
            ON CONFLICT (snapshot_date, country_code)
            DO UPDATE SET top_items = EXCLUDED.top_items, updated_at = now();
        END IF;
    END LOOP;
END;
$$ LANGUAGE plpgsql;

-- 4. Cron Job Example (pg_cron extension required)
-- SELECT cron.schedule('*/30 * * * *', $$SELECT generate_daily_top10(CURRENT_DATE)$$);
