-- ==========================================
-- User Likes Table and Functions
-- ==========================================

-- 1. User Likes Table (사용자 좋아요)
create table if not exists public.user_likes (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  post_id bigint references public.posts(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, post_id)
);

alter table public.user_likes enable row level security;

create policy "Users can view all likes"
  on public.user_likes for select
  using (true);

create policy "Users can insert their own likes"
  on public.user_likes for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own likes"
  on public.user_likes for delete
  using (auth.uid() = user_id);

create index if not exists user_likes_user_id_idx on public.user_likes(user_id);
create index if not exists user_likes_post_id_idx on public.user_likes(post_id);

-- 2. Toggle Like Function (좋아요 토글)
create or replace function public.toggle_like(p_post_id bigint)
returns jsonb as $$
declare
  v_user_id uuid;
  v_liked boolean;
  v_like_count integer;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  -- 기존 좋아요 확인
  select exists(
    select 1 from public.user_likes
    where user_id = v_user_id and post_id = p_post_id
  ) into v_liked;

  if v_liked then
    -- 좋아요 취소
    delete from public.user_likes
    where user_id = v_user_id and post_id = p_post_id;

    update public.posts
    set likes = greatest(0, likes - 1)
    where id = p_post_id;
  else
    -- 좋아요 추가
    insert into public.user_likes (user_id, post_id)
    values (v_user_id, p_post_id)
    on conflict (user_id, post_id) do nothing;

    update public.posts
    set likes = likes + 1
    where id = p_post_id;
  end if;

  -- 최신 좋아요 수 조회
  select likes into v_like_count
  from public.posts
  where id = p_post_id;

  return jsonb_build_object(
    'liked', not v_liked,
    'like_count', v_like_count
  );
end;
$$ language plpgsql security definer
set search_path = public, auth;

grant execute on function public.toggle_like(bigint) to authenticated;

-- 3. Check User Like Function (사용자 좋아요 확인)
create or replace function public.check_user_like(p_post_id bigint)
returns boolean as $$
declare
  v_user_id uuid;
begin
  v_user_id := auth.uid();

  if v_user_id is null then
    return false;
  end if;

  return exists(
    select 1 from public.user_likes
    where user_id = v_user_id and post_id = p_post_id
  );
end;
$$ language plpgsql security definer
set search_path = public, auth;

grant execute on function public.check_user_like(bigint) to authenticated;
